// Fetch start data constants
export const FETCH_BY_ID_START = 'FETCH_BY_ID_START';
export const FETCH_ALL_REGIONS_WEATHER_START = 'FETCH_ALL_REGIONS_WEATHER_START';
export const FETCH_BY_CITY_NAME_START = 'FETCH_BY_CITY_NAME_START';
export const FETCH_BY_COORDS_START = 'FETCH_BY_COORDS_START';

// Fetch success constants
export const FETCH_BY_ID_SUCCESS = 'FETCH_BY_ID_SUCCESS';
export const FETCH_ALL_REGIONS_WEATHER_SUCCESS = 'FETCH_ALL_REGIONS_WEATHER_SUCCESS';
export const FETCH_BY_CITY_NAME_SUCCESS = 'FETCH_BY_CITY_NAME_SUCCESS';
export const FETCH_BY_COORDS_SUCCESS = 'FETCH_BY_COORDS_SUCCESS';

// Error constants
export const ERROR = 'ERROR';
export const FETCH_BY_ID_ERROR = 'FETCH_BY_ID_ERROR';
export const FETCH_ALL_REGIONS_WEATHER_ERROR = 'FETCH_ALL_REGIONS_WEATHER_ERROR';
export const FETCH_BY_CITY_NAME_ERROR = 'FETCH_BY_CITY_NAME_ERROR';
export const FETCH_BY_COORDS_ERROR = 'FETCH_BY_COORDS_ERROR';

// Interaction constants
export const SHOW_WATER = 'SHOW_WATER';
export const SHOW_TEMP = 'SHOW_TEMP';
export const TOGGLE_MENU = 'TOGGLE_MENU';
export const CLOSE_MENU = 'CLOSE_MENU';
export const EXPANDED = 'EXPANDED';
export const CHANGE_CURRENT_REGION = 'CHANGE_CURRENT_REGION';
export const OPEN_DIALOG = 'OPEN_DIALOG';
export const CLOSE_DIALOG = 'CLOSE_DIALOG';
export const FIT_BY_COORDS = 'FIT_BY_COORDS';
export const RESET_FIT = 'RESET_FIT';
export const TOGGLE_FIND_BY_POINT = 'TOGGLE_FIND_BY_POINT';
export const FIND_BY_POINT_OFF = 'FIND_BY_POINT_OFF';
export const TOGGLE_LAYERS_DISPLAY = 'TOGGLE_LAYERS_DISPLAY';
export const SHOW_MESSAGE = 'SHOW_MESSAGE';
export const CLOSE_MESSAGE = 'CLOSE_MESSAGE';